frontEnd/tutor/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.LoginView, name='login'),
    url(r'^loginhandle$', views.LoginHandleView, name='loginhandle'),
    #url(r'^(?P<user_id>[0-9]+)/event/$', views.EventView, name='event'),
    url(r'^(?P<user_id>[0-9]+)/cat/$', views.catView, name='catalog'),
    #url(r'^(?P<user_id>[0-9]+)/search/$', views.searchView, name='search'),
    #url(r'^(?P<user_id>[0-9]+)/rec/$', views.recommendView, name='reccomend'),
    url(r'^(?P<user_id>[0-9]+)/orders/$', views.orderView, name='orders'),
    url(r'^(?P<user_id>[0-9]+)/buy/$', views.createBuyView, name='buyItem'),
    #url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

frontEnd/tutor/tutor/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
        url(r'^polls/', include('polls.urls')),
        url(r'^admin/', admin.site.urls),
]

frontEnd/tutor/polls/models.py
from django.db import models

class Catalog(models.Model):
    cat_desc = models.CharField(max_length=100)
    cat_pid = models.IntegerField(default=0)
    cat_type = models.CharField(max_length=100)
    cat_type_num = models.IntegerField(default=0)
    def __str__(self):
        return self.cat_desc

class Orders(models.Model):
    order_usrID = models.CharField(max_length=25) #Foreign key?
    order_desc = models.CharField(max_length=100)
    order_pid = models.IntegerField(default=0)
    order_wid = models.IntegerField(default=0)
    order_quant = models.IntegerField(default=0)
    order_status = models.IntegerField(default=0)
    order_adrX = models.IntegerField(default=0)
    order_adrY = models.IntegerField(default=0)
    order_upsID = models.IntegerField(default=0)
    def __str__(self):
        return self.order_desc

class User(models.Model):
    #u_type = models.IntegerField(default=1)
    u_email = models.CharField(max_length=200, default='null')
    u_name = models.CharField(max_length=200)
    def __str__(self):
        return self.u_name

class Event(models.Model):
    e_name = models.CharField(max_length=200)
    e_time = models.DateTimeField('event')
    e_date = models.CharField(max_length=200, default='Unknown')
    def __str__(self):
        return self.e_name

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
                return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
            return self.choice_text

frontEnd/tutor/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Choice, Question, User, Catalog, Orders

class IndexView(generic.ListView):
        template_name = 'polls/index.html'
        context_object_name = 'latest_question_list'

        def get_queryset(self):
                """Return the last five published questions."""
                return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
        model = Question
        template_name = 'polls/detail.html'
        
class ResultsView(generic.DetailView):
        model = Question
        template_name = 'polls/results.html'

def catView(request, user_id): #add userID for nicety?
        if request.method == "GET":
                c_list = Catalog.objects.all();
                return render (request, 'polls/catalog.html', {
                        'c_list':c_list,
                        'user_id': user_id,
                })
        else:
                c_list = Catalog.objects.order_by('cat_type_num');
                return render (request, 'polls/catalog.html', {
                        'c_list':c_list,
                        'user_id': user_id,
                })

def orderView(request, user_id): #add userID for nicety?
        if request.method == "GET":
                o_list = Orders.objects.all();
                return render (request, 'polls/orders.html', {
                        'o_list':o_list,
                        'user_id': user_id,
                })
        else:
                return render (request, 'polls/orders.html', {
                        'o_list':o_list,
                        'user_id': user_id,
                })

def createBuyView(request, user_id):
        print("called createBuy")
        cat_pid = request.POST['item']
        desc = request.POST['desc']
        buy_order =    Orders(order_usrID=user_id, order_desc = desc, order_pid = cat_pid, order_status = 0, order_quant = request.POST['quant' + cat_pid], order_adrX = request.POST['adrX'+cat_pid], order_adrY = request.POST['adrY'+cat_pid])
        buy_order.save()
        return HttpResponseRedirect(reverse('polls:catalog', args=(user_id)))

def LoginView(request):
    return render(request, 'polls/login.html')

def LoginHandleView(request):
    if ('username' in request.POST and (len(request.POST['username']) > 0)):
        if ('buttonlogin' in request.POST and User.objects.filter(u_name = request.POST['username'])):
            user = get_object_or_404(User, u_name=request.POST['username'])
            return HttpResponseRedirect(reverse('polls:catalog', args=(user.id, )))
        if ('buttonsign' in request.POST and (not User.objects.filter(u_name = request.POST['username'])) and 'useremail' in request.POST and (len(request.POST['useremail']) > 0)):
            n_user = User(u_email=request.POST['useremail'], u_name=request.POST['username'])
            n_user.save()
    return HttpResponseRedirect(reverse('polls:login', args=()))

def EventView(request, user_id):
    event_list = Event.objects.filter(pee_set__u_id=user_id).order_by('-e_time')
    return render(request, 'polls/event.html', {
                  'event_list': event_list,
                  'user_id': user_id,
                  'user_name': get_object_or_404(User, pk=user_id).u_name,
                  'pe_list': get_object_or_404(User, pk=user_id).peu_set.all(),
                  })




def vote(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
                selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
                # Redisplay the question voting form.
                return render(request, 'polls/detail.html', {
                        'question': question,
                        'error_message': "You didn't select a choice.",
                })
        else:
                selected_choice.votes += 1
                selected_choice.save()
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

frontEnd/tutor/polls/templates/polls/catalog.html
<h1>{{ "Catalog" }}</h1>

{% for c in c_list %}
<fieldset>
  <legend>Item {{ forloop.counter }}</legend>
  <form action="{% url 'polls:buyItem' user_id %}" method ="post">
    {% csrf_token %}
    <div>
      <p> <b> {{c.cat_desc}} </b> </p>
      <!--<p> {{c.cat_pid}} </p>-->
    </div>
    <div style="float:left";>
      <label for="box1{{ forloop.counter }}">Quant</label>
      <input type="text" name="quant{{ c.cat_pid }}" id="box1{{ forloop.counter }}"><br>
      <label for="box2{{ forloop.counter }}">AddrX</label>
      <input type="text" name="adrX{{ c.cat_pid }}" id="box2{{ forloop.counter }}"><br>
      <label for="box3{{ forloop.counter }}">AddrY</label>
      <input type="text" name="adrY{{ c.cat_pid }}" id="box3{{ forloop.counter }}"><br>
      <input type="hidden" name="item" value="{{c.cat_pid}}" />
      <input type="hidden" name="desc" value="{{c.cat_desc}}" />
    </div>
    <input type = "submit" value = "Buy" />
  </form>
</fieldset>
{% endfor %}

<br>

<div style="float:left";>
  <form action="{% url 'polls:orders' user_id %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Orders" />
  </form>
  <form action="{% url 'polls:login' %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Logout" />
  </form>
</div>

frontEnd/tutor/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
  <input type="submit" value="Vote" />
</form>

frontEnd/tutor/polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

frontEnd/tutor/polls/templates/polls/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/login.css' %}" />

<div id="login_frame">
<h1>User Login</h1>
<form action="{% url 'polls:loginhandle' %}", method="post">
  {% csrf_token %}
  <label for="box1">User Name</label><br>
  <input type="text" name="username" id="box1"><br>
  <label for="box1">User Email</label><br>
  <input type="text" name="useremail" id="box"><br>
  <input type="submit" name="buttonlogin" value="Login" />
  <input type="submit" name="buttonsign" value="Sign Up" />
</form>
</div>

frontEnd/tutor/polls/templates/polls/orders.html
<h1>{{ "Order(s)" }}</h1>

{% for o in o_list %}
<fieldset>
  <legend>Order {{ forloop.counter }}</legend>
  <form method action="{% url 'polls:orders' user_id %}">
    <div>
      <p> <b> {{o.order_desc}} </b> </p>
      <p> {{o.order_desc}} </p>
      <p> {{o.order_quant}} </p>
      <p> {{o.order_pid}} </p>
      <p> Status: {{o.order_status}} </p>
    </div>
  </form>
</fieldset>
{% endfor %}

<br>

<form action="{% url 'polls:catalog' user_id %}" method="get">
  {% csrf_token %}
  <input type="submit" value="Back" />
</form>
</div>

frontEnd/tutor/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

frontEnd/tutor/polls/templates/polls/search.html
<h1>{{ "Search" }}</h1>

{% for c in c_list %}
<fieldset>
  <legend>Item {{ forloop.counter }}</legend>
  <form action="{% url 'polls:buyItem' user_id %}" method ="post">
    {% csrf_token %}
    <div>
      <p> <b> {{c.cat_desc}} </b> </p>
      <!--<p> {{c.cat_pid}} </p>-->
    </div>
    <div style="float:left";>
      <label for="box1{{ forloop.counter }}">Quant</label>
      <input type="text" name="quant{{ c.cat_pid }}" id="box1{{ forloop.counter }}"><br>
      <label for="box2{{ forloop.counter }}">AddrX</label>
      <input type="text" name="adrX{{ c.cat_pid }}" id="box2{{ forloop.counter }}"><br>
      <label for="box3{{ forloop.counter }}">AddrY</label>
      <input type="text" name="adrY{{ c.cat_pid }}" id="box3{{ forloop.counter }}"><br>
      <input type="hidden" name="item" value="{{c.cat_pid}}" />
      <input type="hidden" name="desc" value="{{c.cat_desc}}" />
    </div>
    <input type = "submit" value = "Buy" />
  </form>
</fieldset>
{% endfor %}

<br>

<div style="float:left";>
  <form action="{% url 'polls:orders' user_id %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Orders" />
  </form>
  <form action="{% url 'polls:catalog' user_id %}" method="post">
    {% csrf_token %}
  <input type="submit" value="Recommended" />
  </form>
  <form action="{% url 'polls:login' %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Logout" />
  </form>
</div>